typeof progress=="function"&&progress("jet.all.js loaded");
(function(){var c=this,b=c.Jx,p={},o={},k={NO_DEBUG:0,SHOW_ALL:1},e={debug:1},l=function(b,c,i){b=String(b);e.debug&&this.console&&(this.console.out?this.console.out(b,c,i):alert(b+" - \u6d88\u606f\u7c7b\u578b["+i+"]"));return b};try{if(typeof b==="undefined"||b.mark&&b.mark==="JxMark"){if(b)p=b.VERSIONS,o=b.PACKAGES;b=function(c,h){var i=this;if(h)this._init();else if(c){c=String(c);try{if(b.VERSIONS[c])i=b.VERSIONS[c];else throw i=b.VERSIONS[b.DEFAULT_VERSION],Error("\u6ca1\u6709\u627e\u5230 JET version "+
c+", \u6240\u4ee5\u8fd4\u56de\u9ed8\u8ba4\u7248\u672c JET version "+b.DEFAULT_VERSION+"!");}catch(m){i.out("A.\u9519\u8bef\uff1a["+m.name+"] "+m.message+", "+m.fileName+", \u884c\u53f7:"+m.lineNumber+"; stack:"+typeof m.stack,2)}}else i=b.VERSIONS[b.DEFAULT_VERSION];return i};b.prototype={version:"1.0",DEBUG:k,option:e,_init:function(){this.constructor=b},$namespace:function(b){for(var c,i=b.split("."),m=window,b=0;b<i.length;b+=1)c=i[b],m[c]=m[c]||{},m=m[i[b]];return m},$package:function(){var f=
arguments[0],h=arguments[arguments.length-1],i=c;if(typeof h==="function")typeof f==="string"?(i=this.$namespace(f),b.PACKAGES[f]||(b.PACKAGES[f]={isLoaded:!0,returnValue:void 0}),i.packageName=f):typeof f==="object"&&(i=f),h.call(i,this);else throw Error("Function required");},checkPackage:function(c){return b.PACKAGES[c]},out:l,debug:function(){},profile:function(){},warn:function(){},error:function(){},startTime:+new Date,about:function(){return this.out("JET (Javascript Extend Tools)\nversion: "+
this.version+"\n\nCopyright (c) 2009, All rights reserved.")},toString:function(){return"JET version "+this.version+" !"}};b.VERSIONS=p;b.PACKAGES=o;b.VERSIONS["1.0"]=new b("1.0",!0);b.DEFAULT_VERSION="1.0";b.mark="JxMark";c.Jet=c.Jx=b}else throw Error('"Jx" name is defined in other javascript code !!!');}catch(h){l("JET \u5fae\u5185\u6838\u521d\u59cb\u5316\u5931\u8d25! B.\u9519\u8bef\uff1a["+h.name+"] "+h.message+", "+h.fileName+", \u884c\u53f7:"+h.lineNumber+"; stack:"+typeof h.stack,1)}})();
Jx().$package(function(c){var b,p,o,k,e,l,h,f,q,i,m;b=function(a){return typeof a==="undefined"};p=function(a){return a===null};o=function(a){return(a===0||a)&&a.constructor===Number};e=function(a){return(a===!1||a)&&a.constructor===Boolean};k=function(a){return(a===""||a)&&a.constructor===String};l=function(a){return a&&a.constructor===Object||String(a)==="[object Object]"};h=function(a){return a&&a.constructor===Array||Object.prototype.toString.call(a)==="[object Array]"};f=function(a){return a&&
a.callee&&o(a.length)?!0:!1};q=function(a){return a&&a.constructor===Function};i=function(a,d,g){var j=arguments,b,c;j.length===1?(a=this,j=0):(a=j[0]||{},j=1);for(;j<arguments.length;j++)for(b in c=arguments[j],c){var m=a[b],f=c[b];m!==f&&(f&&l(f)&&!h(f)&&!f.nodeType&&!q(f)?(m=a[b]||{},a[b]=i(m,f||(f.length!=null?[]:{}))):f!==void 0&&(a[b]=f))}return a};m=function(){var a=arguments.length,d=arguments[a-1];d.init=d.init||function(){};if(a===2){var a=arguments[0].extend,g=function(){};g.prototype=
a.prototype;var j=function(){this.init.apply(this,arguments)};j.superClass=a.prototype;j.callSuper=function(a,d){var g=Array.prototype.slice,b=g.call(arguments,2);(d=j.superClass[d])&&d.apply(a,b.concat(g.call(arguments)))};j.prototype=new g;j.prototype.constructor=j;c.extend(j.prototype,d);j.prototype.init=function(){d.init.apply(this,arguments)};return j}else if(a===1)return a=function(){return this.init.apply(this,arguments)},a.prototype=d,a};var n=new m({init:function(a,d,g,j,b){var c=a.concat();
j&&(c=a);this.timeout=window.setTimeout(function(){var j=+new Date;do d.call(g,c.shift());while(c.length>0&&+new Date-j<50);c.length>0?this.timeout=window.setTimeout(arguments.callee,25):b&&b(a)},25)},stop:function(){clearTimeout(this.timeout)}});c.isUndefined=b;c.isNull=p;c.isNumber=o;c.isString=k;c.isBoolean=e;c.isObject=l;c.isArray=h;c.isArguments=f;c.isFunction=q;c.$typeof=function(a){return b(a)?"undefined":p(a)?"null":o(a)?"number":e(a)?"boolean":k(a)?"string":l(a)?"object":h(a)?"array":f(a)?
"arguments":q(a)?"function":"other"};c.$return=function(a){return c.isFunction(a)?a:function(){return a}};c.$try=function(){var a,d=arguments.length,g;for(a=0;a<d;a++)try{g=arguments[a]();break}catch(j){c.out("C.\u9519\u8bef\uff1a["+j.name+"] "+j.message+", "+j.fileName+", \u884c\u53f7:"+j.lineNumber+"; stack:"+typeof j.stack,2)}return g};c.emptyFunc=function(){};c.clone=function(a){var d=function(){};d.prototype=a;return new d};c.getLength=function(a){var d,g=0;for(d in a)a.hasOwnProperty(d)&&g++;
return g};c.checkJSON=function(){return!0};c.random=function(a,d){return Math.floor(Math.random()*(d-a+1)+a)};c.extend=i;c.now=function(){return+new Date};c.timedChunk=function(a,d,g,j,b){var c=a.concat();j&&(c=a);window.setTimeout(function(){var j=+new Date;do d.call(g,c.shift());while(c.length>0&&+new Date-j<50);c.length>0?window.setTimeout(arguments.callee,25):b&&b(a)},25)};c.rebuild=function(a,d){d=d||{};a.$$rebuildedFunc=a.$$rebuildedFunc||function(){var g,j;g=d.contextObj||this;j=Array.prototype.slice.call(arguments,
0);j!==void 0&&(j=j.concat(d.arguments));d.event===!1&&(j=j.slice(1));return a.apply(g,j)};return a.$$rebuildedFunc};c.pass=function(a,d){var g=Array.prototype.slice,j=g.call(arguments,1);return function(){return a.apply(this,j.concat(g.call(arguments)))}};c.bind=function(a,d,g){var j=Array.prototype.slice,b=j.call(arguments,2);return function(){return a.apply(d,b.concat(j.call(arguments)))}};c.bindNoEvent=void 0;c.Class=m;c.Chunk=n});
Jx().$package(function(c){c.browserOptions={adjustBehaviors:!0,htmlClass:!0};c.host=window.location.host;var b=navigator.platform.toLowerCase(),p=navigator.userAgent.toLowerCase(),o=navigator.plugins,k,e,l,h,f;h=function(b,c){b=(""+b).replace(/_/g,".");c=c||1;b=String(b).split(".");b=b[0]+"."+(b[1]||"0");return b=Number(b).toFixed(c)};k={getPlatform:function(){return b},name:window.orientation!=void 0?"iPod":(b.match(/mac|win|linux/i)||["unknown"])[0],version:0,iPod:0,iPad:0,iPhone:0,android:0,win:0,
linux:0,mac:0,set:function(b,c){this.name=b;this.version=c;this[b]=c}};k[k.name]=!0;(f=p.match(/windows ([\d.]+)/))?k.set("win",h(f[1])):(f=p.match(/windows nt ([\d.]+)/))?k.set("win",h(f[1])):(f=p.match(/linux ([\d.]+)/))?k.set("linux",h(f[1])):(f=p.match(/mac ([\d.]+)/))?k.set("mac",h(f[1])):(f=p.match(/ipod ([\d.]+)/))?k.set("iPod",h(f[1])):(f=p.match(/ipad[\D]*os ([\d_]+)/))?k.set("iPad",h(f[1])):(f=p.match(/iphone ([\d.]+)/))?k.set("iPhone",h(f[1])):(f=p.match(/android ([\d.]+)/))&&k.set("android",
h(f[1]));e={features:{xpath:!!document.evaluate,air:!!window.runtime,query:!!document.querySelector},getPlugins:function(){return o},plugins:{flash:function(){var b=0;if(o&&o.length){var c=o["Shockwave Flash"];c&&c.description&&(b=h(c.description.match(/\b(\d+)\.\d+\b/)[1],1)||b)}else for(c=13;c--;)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+c);b=h(c);break}catch(a){}return b}()},getUserAgent:function(){return p},name:"unknown",version:0,ie:0,firefox:0,chrome:0,opera:0,safari:0,mobileSafari:0,
adobeAir:0,set:function(b,c){this.name=b;this.version=c;this[b]=c}};(f=p.match(/msie ([\d.]+)/))?e.set("ie",h(f[1])):(f=p.match(/firefox\/([\d.]+)/))?e.set("firefox",h(f[1])):(f=p.match(/chrome\/([\d.]+)/))?e.set("chrome",h(f[1])):(f=p.match(/opera.([\d.]+)/))?e.set("opera",h(f[1])):(f=p.match(/adobeair\/([\d.]+)/))?e.set("adobeAir",h(f[1])):(f=p.match(/version\/([\d.]+).*safari/))&&e.set("safari",h(f[1]));(f=p.match(/version\/([\d.]+).*mobile.*safari/))&&e.set("mobileSafari",h(f[1]));k.iPad&&e.set("mobileSafari",
"0.0");if(e.ie)document.documentMode?document.documentMode!==Math.floor(e.ie)&&e.set("ie",h(document.documentMode)):document.documentMode=Math.floor(e.ie);l={name:"unknown",version:0,trident:0,gecko:0,webkit:0,presto:0,set:function(b,c){this.name=b;this.version=c;this[b]=c}};(f=p.match(/trident\/([\d.]+)/))?l.set("trident",h(f[1])):(f=p.match(/gecko\/([\d.]+)/))?l.set("gecko",h(f[1])):(f=p.match(/applewebkit\/([\d.]+)/))?l.set("webkit",h(f[1])):(f=p.match(/presto\/([\d.]+)/))&&l.set("presto",h(f[1]));
e.ie&&(e.ie==6?l.set("trident",h("4")):(e.ie==7||e.ie==8)&&l.set("trident",h("5")));if(c.browserOptions.adjustBehaviors&&e.ie&&e.ie<7)try{document.execCommand("BackgroundImageCache",!1,!0)}catch(q){}var i=function(b){return String(b).replace(/\./gi,"_")};c.browserOptions.htmlClass&&function(){var b=document.documentElement,c=[b.className];c.push("javascriptEnabled");c.push(k.name);c.push(k.name+i(k.version));c.push(e.name);c.push(e.name+i(e.version));document.documentMode&&c.push("documentMode_"+
document.documentMode);c.push(l.name);c.push(l.name+i(l.version));e.plugins.flash&&(c.push("flash"),c.push("flash"+i(e.plugins.flash)));typeof window.webTop!="undefined"&&window.webTop&&c.push("webTop");b.className=c.join(" ")}();c.platform=k;c.browser=e;c.browser.engine=l});
Jx().$package(function(c){var b,p,o,k,e,l,h,f,q,i,m,n,a,d,g,j=null,v,u,w,s;c.dom=c.dom||{};b=c.dom;p=b.win?b.win.contentWindow:b.win||window;b.win=p;b.doc=p.document;var r=document&&Object.prototype.hasOwnProperty.call(document.documentElement,"classList");u=function(){return w?w:w=document.compatMode==="CSS1Compat"?document.documentElement:document.body};g=function(a){a?(a=a||window.document,j=a.nodeType===9?a:a.ownerDocument||b.doc):j||(a=a||window.document,j=a.nodeType===9?a:a.ownerDocument||b.doc);
return j};v=function(a){var d=g(a);return a.document?a:d.defaultView||d.parentWindow||b.win};p=function(a,d){d=d||g();return d.getElementsByTagName(a)};i=function(a){return(a?a.scrollLeft:Math.max(document.documentElement.scrollLeft,document.body.scrollLeft))||0};m=function(a){return(a?a.scrollTop:Math.max(document.documentElement.scrollTop,document.body.scrollTop))||0};o=function(){return r?function(a,d){return!a||!d?!1:a.classList.contains(d)}:function(a,d){return!a||!d?!1:-1<(" "+a.className+" ").indexOf(" "+
d+" ")}}();k=function(){return r?function(a,d){a&&d&&!o(a,d)&&a.classList.add(d)}:function(a,d){a&&d&&!o(a,d)&&(a.className+=" "+d)}}();e=function(){return r?function(a,d){a&&d&&o(a,d)&&a.classList.remove(d)}:function(a,d){if(a&&d&&o(a,d))a.className=a.className.replace(RegExp("(?:^|\\s)"+d+"(?:\\s|$)")," ")}}();l=function(){return r?function(a,d){a&&d&&a.classList.toggle(d)}:function(a,d){a&&d&&(o(a,d)?e(a,d):k(a,d))}}();h=function(a,d,g){if(a){var b=c.browser.name;if(d==="float"||d==="cssFloat")d=
b==="ie"?"styleFloat":"cssFloat";if(d==="opacity"&&b==="ie"&&c.browser.ie<9){if(a.style.filter='alpha(opacity="'+g*100+'")',!a.style.zoom)a.style.zoom=1}else a.style[d]=g}};f=function(a,d){if(a){var g=v(a),b=c.browser.name;if(d==="float"||d==="cssFloat")d=b==="ie"?"styleFloat":"cssFloat";if(d==="opacity"&&b==="ie"&&c.browser.ie<9)return g=1,(b=a.style.filter.match(/opacity=(\d+)/))&&b[1]&&(g=b[1]/100),g;if(a.style[d])return a.style[d];else if(a.currentStyle)return a.currentStyle[d];else if(g.getComputedStyle)return g.getComputedStyle(a,
null)[d];else if(document.defaultView&&document.defaultView.getComputedStyle)return d=d.replace(/([/A-Z])/g,"-$1"),d=d.toLowerCase(),(g=document.defaultView.getComputedStyle(a,""))&&g.getPropertyValue(d)}};q=function(a,d){a.style.cssText=d};n=function(a){var d=0,g=0;if(a)if(document.documentElement.getBoundingClientRect&&a.getBoundingClientRect){g={left:0,top:0,right:0,bottom:0};try{g=a.getBoundingClientRect()}catch(b){return[0,0]}var a=a.ownerDocument,j=c.browser.ie?2:0,d=g.top-j+m(a),g=g.left-j+
i(a)}else for(;a.offsetParent;)d+=a.offsetTop,g+=a.offsetLeft,a=a.offsetParent;return[g,d]};a=function(a){a=n(a);a[0]+=i();a[1]+=m();return a};d=function(a,d,g){var b=parseInt(f(a,"marginLeft"))||0,c=parseInt(f(a,"marginTop"))||0;h(a,"left",parseInt(d)-b+"px");h(a,"top",parseInt(g)-c+"px")};for(var t=function(a){return!a||a=="auto"?0:parseInt(a.substr(0,a.length-2))},x=p("script"),y=0;y<x.length;y++)if(x[y].getAttribute("hasJx")=="true")c.src=x[y].src;if(!c.src)c.src=x[x.length-1].src;c.filename=
c.src.replace(/(.*\/){0,}([^\\]+).*/ig,"$2");c.path=c.src.split(c.filename)[0];b.getDoc=g;b.id=function(a,d){return g(d).getElementById(a)};b.name=function(a,d){return g(d).getElementsByName(a)};b.tagName=p;b.getText=function(a){var d=a?a[TEXT_CONTENT]:"";d===UNDEFINED&&INNER_TEXT in a&&(d=a[INNER_TEXT]);return d||""};b.getAttributeByParent=function(a,d,g){var b=!1,j;do j=d.getAttribute(a),c.isUndefined(j)||c.isNull(j)?d===g?b=!0:d=d.parentNode:b=!0;while(!b);return j};b.node=function(a,d){var g,
b=document.createElement(a),c={"class":function(){b.className=d["class"]},style:function(){q(b,d.style)}};for(g in d)if(c[g])c[g]();else b.setAttribute(g,d[g]);return b};b.setClass=function(a,d){a.className=d};b.getClass=function(a){return a.className};b.hasClass=o;b.addClass=k;b.removeClass=e;b.toggleClass=l;b.replaceClass=function(a,d,g){e(a,d);k(a,g)};b.createStyleNode=function(a,d){var g=b.node("style",{id:d||"",type:"text/css"});if(g.styleSheet)g.styleSheet.cssText=a;else{var c=document.createTextNode(a);
g.appendChild(c)}b.getDocHead().appendChild(g);return g};b.setStyle=h;b.getStyle=f;b.setCssText=q;b.getCssText=function(a){return a.style.cssText};b.addCssText=function(a,d){a.style.cssText+=";"+d};b.show=function(a,d){var g;g=(g=a.getAttribute("_oldDisplay"))?g:f(a,"display");d?h(a,"display",d):g==="none"?h(a,"display","block"):h(a,"display",g)};b.isShow=function(a){return f(a,"display")==="none"?!1:!0};b.recover=function(a){var d;d=(d=a.getAttribute("_oldDisplay"))?d:f(a,"display");d==="none"?h(a,
"display",""):h(a,"display",d)};b.hide=function(a){var d=f(a,"display");a.getAttribute("_oldDisplay")||(d==="none"?a.setAttribute("_oldDisplay",""):a.setAttribute("_oldDisplay",d));h(a,"display","none")};b.getScrollLeft=i;b.getScrollTop=m;b.getScrollHeight=function(a){return(a?a.scrollHeight:Math.max(document.documentElement.scrollHeight,document.body.scrollHeight))||0};b.getScrollWidth=function(a){return(a?a.scrollWidth:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth))||0};
b.getClientHeight=function(a){a=a||u();return a.clientHeight};b.getClientWidth=function(a){a=a||u();return a.clientWidth};b.getOffsetHeight=function(a){a=a||u();return a.offsetHeight};b.getOffsetWidth=function(a){a=a||u();return a.offsetWidth};b.getClientXY=n;b.setClientXY=function(a,g,b){g=parseInt(g)+i();b=parseInt(b)+m();d(a,g,b)};b.getXY=a;b.setXY=d;b.getRelativeXY=function(d,g){var b=a(d),c=a(g),j=[];j[0]=b[0]-c[0];j[1]=b[1]-c[1];return j};b.getPosX=function(a){return t(b.getStyle(a,"left"))};
b.getPosY=function(a){return t(b.getStyle(a,"top"))};b.getWidth=function(a){return t(b.getStyle(a,"width"))};b.getHeight=function(a){return t(b.getStyle(a,"height"))};b.getSelection=void 0;b.getSelectionText=function(a){var a=a||window,d=a.document;if(a.getSelection)return a.getSelection().toString();else if(d.getSelection)return d.getSelection();else if(d.selection)return d.selection.createRange().text};b.getTextFieldSelection=function(a){return a.selectionStart!=void 0&&a.selectionEnd!=void 0?a.value.substring(a.selectionStart,
a.selectionEnd):""};b.getDocumentElement=u;b.getDocHead=function(){if(!s){var a=g();s=a.getElementsByTagName("head")?a.getElementsByTagName("head")[0]:a.documentElement}return s};b.contains=function(a,d,g){if(!g&&a===d)return!1;if(a.compareDocumentPosition){if(a=a.compareDocumentPosition(d),a==20||a==0)return!0}else if(a.contains(d))return!0;return!1}});
Jx().$package(function(c){var b,p,o,k,e,l,h=[],f,q,i,m,n;c.event=c.event||{};b=c.event;n=function(a,d){if(!a)a=window.event;var d=d||a.srcElement,g=document,b=g.documentElement,g=g.body,b={_event:a,type:a.type,target:a.srcElement,currentTarget:d,relatedTarget:a.fromElement?a.fromElement:a.toElement,eventPhase:a.srcElement==d?2:3,clientX:a.clientX,clientY:a.clientY,screenX:a.screenX,screenY:a.screenY,layerX:a.offsetX,layerY:a.offsetY,pageX:a.clientX+(b&&b.scrollLeft||g&&g.scrollLeft||0)-(b&&b.clientLeft||
g&&g.clientLeft||0),pageY:a.clientY+(b&&b.scrollTop||g&&g.scrollTop||0)-(b&&b.clientTop||g&&g.clientTop||0),wheelDelta:a.wheelDelta||-40*(a.detail||0),altKey:a.altKey,ctrlKey:a.ctrlKey,shiftKey:a.shiftKey,charCode:a.keyCode,keyCode:a.keyCode,stopPropagation:function(){this._event.cancelBubble=!0},preventDefault:function(){this._event.returnValue=!1}},g=a.type.toLowerCase();if(g=="mouseover")b.relatedTarget=a.fromElement;else if(g=="mouseout")b.relatedTarget=a.toElement;if(!c.isUndefined(a.button)){var g=
a.button,i={0:-1,1:0,2:2,3:-1,4:1};b.button=c.isUndefined(i[g])?g:i[g]}return b};c.browser.ie?(p=function(a,d,g,b){if(l["on"+d])l["on"+d](a,d,g,b);else o(a,d,g)},o=function(a,d,g){if(b._find(arguments)==-1){var c=function(d){d=n(d,a);Function.prototype.call?g.call(a,d):(a._currentHandler=g,a._currentHandler(d),a._currentHandler=null)};a.attachEvent("on"+d,c);var c={element:a,eventType:d,handler:g,wrappedEvent:c},i=(a.document||a).parentWindow||window,f=b._uid();if(!i._allHandlers)i._allHandlers={};
i._allHandlers[f]=c;if(!a._handlers)a._handlers=[];a._handlers.push(f);if(!i._onunloadEventRegistered)i._onunloadEventRegistered=!0,i.attachEvent("onunload",b._removeAllEvents)}},k=function(a,d,g){if(l["off"+d])l["off"+d](a,d,g);else arguments.length==3?e(a,d,g):e(a,d)},e=function(a,d,g){var c=b._find(arguments);if(c!=-1){for(var i=(a.document||a).parentWindow||window,f=0;f<c.length;f++){var h=c[f],m=a._handlers[h],n=i._allHandlers[m];a.detachEvent("on"+n.eventType,n.wrappedEvent);a._handlers[h]=
null;a._handlers.splice(h,1);delete i._allHandlers[m]}if(a._handlers&&a._handlers.length==0)a._handlers=null}},b._find=function(a){var d=a[0],g=a[1],b=a[2],c=d._handlers;if(!c)return-1;var d=(d.document||d).parentWindow||window,i=[];if(a.length===3)for(a=c.length-1;a>=0;a--){var f=c[a],f=d._allHandlers[f];if(f.eventType==g&&f.handler==b)return i.push(a),i}else if(a.length===2){for(a=c.length-1;a>=0;a--)f=c[a],f=d._allHandlers[f],f.eventType==g&&i.push(a);if(i.length>0)return i}else if(a.length===
1){for(a=c.length-1;a>=0;a--)i.push(a);if(i.length>0)return i}return-1},b._removeAllEvents=function(){for(var a in this._allHandlers){var d=this._allHandlers[a];d.element.detachEvent("on"+d.eventType,d.wrappedEvent);d.element._handlers=null;delete this._allHandlers[a]}},b._counter=0,b._uid=function(){return"h"+b._counter++}):document.addEventListener&&(p=function(a,d,g,b){if(l["on"+d])l["on"+d](a,d,g,b);else o(a,d,g)},o=function(a,d,g){var b=!1;a||c.out("targetModel undefined:"+d+g);if(!a._eventTypes)a._eventTypes=
{};a._eventTypes[d]||(a._eventTypes[d]=[]);a.addEventListener(d,g,!1);a=a._eventTypes[d];for(d=0;d<a.length;d++)if(a[d]==g){b=!0;break}b||a.push(g)},k=function(a,d,g){if(l["off"+d])l["off"+d](a,d,g);else arguments.length==3?e(a,d,g):e(a,d)},e=function(a,d,g){if(d)if(arguments.length==3){if(g&&(a.removeEventListener(d,g,!1),a._eventTypes&&a._eventTypes[d]))for(var b=a._eventTypes[d],c=0;c<b.length;c++)if(b[c]===g){b[c]=null;b.splice(c,1);break}}else{if(a._eventTypes&&a._eventTypes[d]){b=a._eventTypes[d];
for(c=0;c<b.length;c++)a.removeEventListener(d,b[c],!1);a._eventTypes[d]=[]}}else if(a._eventTypes){var i=a._eventTypes,f;for(f in i){b=a._eventTypes[f];for(c=0;c<b.length;c++)a.removeEventListener(f,b[c],!1)}}});l={ondrag:function(a,d,g){var j,i,f=!1,m=function(d){if(c.browser.mobileSafari||d.button===0)c.browser.mobileSafari?(d.stopPropagation(),d=d.touches[0],j=d.pageX,i=d.pageY):(d.stopPropagation(),d.preventDefault(),j=d.clientX,i=d.clientY),f=!1,c.browser.mobileSafari?(b.addEventListener(document,
"touchmove",n),b.addEventListener(a,"touchend",e)):b.addEventListener(document,"mousemove",n)},n=function(d){if(c.browser.mobileSafari||d.button===0){var m,h;d.stopPropagation();c.browser.mobileSafari?(h=d.changedTouches[0],m=h.pageX,h=h.pageY):(m=d.clientX,h=d.clientY);Math.abs(j-m)+Math.abs(i-h)>2&&(c.browser.mobileSafari?(b.removeEventListener(document,"touchmove",n),b.removeEventListener(a,"touchend",e)):b.removeEventListener(document,"mousemove",n),f||(g.call(a,d),f=!0))}},e=function(a){if(c.browser.mobileSafari||
a.button===0)c.browser.mobileSafari?(b.removeEventListener(document,"touchmove",n),f&&(a.stopPropagation(),a.preventDefault())):b.removeEventListener(document,"mousemove",n)};c.browser.mobileSafari?b.addEventListener(a,"touchstart",m):(b.addEventListener(a,"mousedown",m),b.addEventListener(a,"mouseup",e));h.push({element:a,eventType:d,handler:g,actions:[m,e]})},offdrag:function(a,d,g){for(var j in h)if(h[j].handler==g&&h[j].element==a&&h[j].eventType==d){c.browser.mobileSafari?(b.removeEventListener(a,
"touchstart",h[j].actions[0]),b.removeEventListener(a,"touchend",h[j].actions[1])):(b.removeEventListener(a,"mousedown",h[j].actions[0]),b.removeEventListener(a,"mouseup",h[j].actions[1]));h.splice(j,1);break}},oncustomclick:function(a,d,g,j){var i,f,m=!1,n=!1,e,j=j?j:{},p=j.longtouchable,q=-1,j=function(d){m=!1;if(c.browser.mobileSafari||d.button===0){var j;c.browser.mobileSafari?(j=d.changedTouches[0],i=j.pageX,f=j.pageY):(i=d.clientX,f=d.clientY);n=!1;p&&(e=setTimeout(function(){!m&&!n&&(c.browser.mobileSafari?
(b.removeEventListener(a,"touchmove",o),b.removeOriginalEventListener(a,"touchend",l)):(b.removeEventListener(a,"mousemove",o),b.removeOriginalEventListener(a,"click",l)),g.call(a,d,2E3))},1E3));c.browser.mobileSafari?(b.addEventListener(a,"touchmove",o),b.addOriginalEventListener(a,"touchend",l)):(b.addEventListener(a,"mousemove",o),b.addOriginalEventListener(a,"click",l))}},k=function(a){q=a.button;if(c.browser.mobileSafari||a.button===0)c.browser.mobileSafari&&(touch=a.changedTouches[0])},o=function(d){if(c.browser.mobileSafari){touch=
d.changedTouches[0];var g=touch.pageX,d=touch.pageY}else g=d.clientX,d=d.clientY;if(m=Math.abs(i-g)+Math.abs(f-d)>1)clearTimeout(e),e=null,c.browser.mobileSafari?(b.removeEventListener(a,"touchmove",o),b.removeOriginalEventListener(a,"touchend",l)):(b.removeEventListener(a,"mousemove",o),b.removeOriginalEventListener(a,"click",l))},l=function(d){clearTimeout(e);e=null;n=!0;if(c.browser.mobileSafari||q===0){var b;if(c.browser.mobileSafari){b=d.changedTouches[0];var j=b.pageX;b=b.pageY}else j=d.clientX,
b=d.clientY;Math.abs(i-j)+Math.abs(f-b)<1&&(m=!1,g.call(a,d,0))}};c.browser.mobileSafari?b.addEventListener(a,"touchstart",j):(b.addEventListener(a,"mousedown",j),b.addEventListener(a,"mouseup",k));h.push({element:a,eventType:d,handler:g,actions:[j,o,k,l]})},offcustomclick:function(a,d,g){for(var j in h)if(h[j].handler==g&&h[j].element==a&&h[j].eventType==d){c.browser.mobileSafari?(b.removeEventListener(a,"touchstart",h[j].actions[0]),b.removeEventListener(a,"touchmove",h[j].actions[1]),b.removeOriginalEventListener(a,
"touchend",h[j].actions[3])):(b.removeEventListener(a,"mousedown",h[j].actions[0]),b.removeEventListener(a,"mousemove",h[j].actions[1]),b.removeEventListener(a,"mouseup",h[j].actions[2]),b.removeOriginalEventListener(a,"click",h[j].actions[3]));h.splice(j,1);break}},oncontextmenu:function(a,d,g){if(c.browser.ie==9){var j=function(d){d=n(d,a);g.call(a,d)};a.attachEvent("oncontextmenu",j);h.push({element:a,eventType:d,handler:g,actions:[j]})}else b.addOriginalEventListener(a,d,g)},offcontextmenu:function(a,
d,g){if(c.browser.ie==9)for(var j in h){if(h[j].handler==g&&h[j].element==a&&h[j].eventType==d){a.detachEvent("oncontextmenu",h[j].actions[0]);h.splice(j,1);break}}else b.removeOriginalEventListener(a,d,g)},onmousewheel:function(a,d,g){if(c.browser.firefox){var j=function(d){d=n(d,a);g.call(a,d)};b.addOriginalEventListener(a,"DOMMouseScroll",j);h.push({element:a,eventType:d,handler:g,actions:[j]})}else b.addOriginalEventListener(a,"mousewheel",g)},offmousewheel:function(a,d,g){if(c.browser.firefox)for(var j in h){if(h[j].handler==
g&&h[j].element==a&&h[j].eventType==d){b.removeOriginalEventListener(a,"DOMMouseScroll",h[j].actions[0]);h.splice(j,1);break}}else b.removeOriginalEventListener(a,"mousewheel",g)},onmouseenter:function(a,d,g){var c=function(a){var d=a.relatedTarget;if(d)if(this.compareDocumentPosition){var b=this.compareDocumentPosition(d);d==this||b==20||b==0||g.call(this,a)}else d==this||this.contains(d)||g.call(this,a);else g.call(this,a)};b.addEventListener(a,"mouseover",c);h.push({element:a,eventType:d,handler:g,
actions:[c]})},offmouseenter:function(a,d,g){for(var c in h)if(h[c].handler==g&&h[c].element==a&&h[c].eventType==d){b.removeEventListener(a,"mouseover",h[c].actions[0]);h.splice(c,1);break}},onmouseleave:function(a,d,g){var c=function(a){var d=a.relatedTarget;d?this.compareDocumentPosition?(d=this.compareDocumentPosition(d),d==20||d==0||g.call(this,a)):this.contains(d)||g.call(this,a):g.call(this,a)};b.addEventListener(a,"mouseout",c);h.push({element:a,eventType:d,handler:g,actions:[c]})},offmouseleave:function(a,
d,g){for(var c in h)if(h[c].handler==g&&h[c].element==a&&h[c].eventType==d){b.removeEventListener(a,"mouseout",h[c].actions[0]);h.splice(c,1);break}}};f=function(a){if(f.done)return a();f.timer?f.ready.push(a):(f.ready=[a],b.on(window,"load",q),f.timer=window.setInterval(q,300))};q=function(){if(f.done)return!0;if(document&&document.getElementsByTagName&&document.getElementById&&document.body){f.done=!0;window.clearInterval(f.timer);f.timer=null;for(var a=0;a<f.ready.length;a++)f.ready[a]();f.ready=
null;return!0}};i=function(){this.subscribers=[]};i.prototype.subscribe=function(a){c.array.some(this.subscribers,function(d){return d===a})||this.subscribers.push(a);return a};i.prototype.deliver=function(a){c.array.forEach(this.subscribers,function(d){d(a)})};i.prototype.unsubscribe=function(a){this.subscribers=c.array.filter(this.subscribers,function(d){return d!==a});return a};m=function(a,d,b){var j,i;if(b){d="on"+d;if(!a._$events)a._$events={};a._$events[d]?a._$events[d].length==0&&(a._$events[d]=
[]):a._$events[d]=[];a=a._$events[d];d=a.length;j=-1;for(i=0;i<d;i++)if(a[i]==b){j=i;break}j===-1&&a.push(b)}else c.out(">>> \u6dfb\u52a0\u7684\u89c2\u5bdf\u8005\u65b9\u6cd5\u4e0d\u5b58\u5728\uff1a"+a+d+b)};b.addEventListener=p;b.removeEventListener=k;b.addOriginalEventListener=o;b.removeOriginalEventListener=e;b.on=b.addEventListener;b.off=b.removeEventListener;b.onDomReady=f;b.Publish=i;b.addObserver=m;b.addObservers=function(a){var d=a.targetModel,a=a.eventMapping,b;for(b in a)m(d,b,a[b])};b.notifyObservers=
function(a,d,b){var c,d="on"+d,i=!0;if(a._$events&&a._$events[d]&&(d=a._$events[d],d.length>0))for(c=0;c<d.length;c++)d[c].apply(a,[b])===!1&&(i=!1);return i};b.removeObserver=function(a,d,b){var c,i=!1,f,m=a._$events;if(b){if(m&&(a=m["on"+d])){f=a.length;for(c=0;c<f;c++)if(a[c]==b){a[c]=null;a.splice(c,1);i=!0;break}}}else if(d){if(m&&(d="on"+d,a=m[d])){f=a.length;for(c=0;c<f;c++)a[c]=null;delete m[d];i=!0}}else if(a&&m){for(c in m)delete m[c];delete a._$events;i=!0}return i}});
Jx().$package(function(c){c.date=c.date||{};c.date.format=function(b,c){var o={"M+":b.getMonth()+1,"D+":b.getDate(),"h+":b.getHours(),"m+":b.getMinutes(),"s+":b.getSeconds(),"q+":Math.floor((b.getMonth()+3)/3),S:b.getMilliseconds()};/(Y+)/.test(c)&&(c=c.replace(RegExp.$1,(b.getFullYear()+"").substr(4-RegExp.$1.length)));for(var k in o)RegExp("("+k+")").test(c)&&(c=c.replace(RegExp.$1,RegExp.$1.length==1?o[k]:("00"+o[k]).substr((""+o[k]).length)));return c}});
Jx().$package(function(c){var b=c.Class({init:function(){var b=this;this.op=[{".":function(b,c){return c.className==b},"+":function(b,c){return c.getAttribute(b)},"#":function(b,c){return c.id==b},".~":function(b,c){return $D.hasClass(c,b)}},{">":function(c,k){var e,l,h;h=c.split(">");l=h[0];h=h[1];return(h=="*"||b.match(h,k))&&(e=b.operate(b.detectAncestor,l,k)())?b.packEvent(k,e):!1}},{"!":function(c,k){c=c.substr(1);return!b.match(c,k)}},{"&&":function(c,k){var e,l;l=c.split("&&");e=l[0];l=l.slice(1).join("");
return b.match(e,k)?l.indexOf("&&")==-1?b.match(l,k):arguments.callee(l,k):!1}}];this.op2Level=[[".","#","+",".~"],">","!","&&"]},detectAncestor:function(b,c,k){var e=5,l=c.target;return function(){if(k(b,l))return l;else if(e>0)return e--,l.parentNode?l=l.parentNode:e=0,arguments.callee();return null}},detect:function(b,c,k){var e=c.target;if(e.nodeType!=1){if(e=e.parentNode,k(b,e))return this.packEvent(c,e)}else return k(b,e);return!1},packEvent:function(b,c){return[!0,{target:c,oTarget:b.target,
stopPropagation:function(){b.stopPropagation()},preventDefault:function(){b.preventDefault()},pageX:b.pageX,pageY:b.pageY}]},operate:function(b,c,k){for(var e,l=3;l>0;){if(e=this.op[0][c.substr(0,l)]){var h=null;if(h=b(c.substr(l),k,e))return h}l--}return!1},match:function(b,c){for(var k=this.op2Level.length;k>0;k--){var e=this.op2Level[k];if(b.indexOf(e)!=-1)return this.op[k][e](b,c,void 0)}return this.operate(this.detect,b,c)},router:function(b,c,k){for(var b=b.split(","),e,k=b.length-1;k>=0;k--)if(e=
this.match(b[k],c))return e;return!1},parse:function(b,c,k){b=this.router(b,k);b.length==2?c(b[1]):b&&c(k)}});c.event.eventParser=new b});
Jx().$package(function(c){var b=c.event,p={"#":"id",".":"className","@":"el","!":"!"},o={blur:1,focus:1,change:1};c.event.eventProxy=function(k,e){var l={},h,f;for(h in e){f=e[h];var q=h.split(" "),i=q[0],q=q[1];l[q]=l[q]||[];l[q].push([i,f])}h=f=null;for(h in l)if(f=l[h],o[h]||h.charAt(0)=="@")for(q=f.length-1;q>=0;q--)for(var i=f[q][0].split(","),m=i.length-1;m>=0;m--){var n=p[i[m].charAt(0)];if(n=="id")b.on($D.id(i[m].substr(1)),h,f[q][1]);else if(n=="el")b.on(k,h.substr(1),f[q][1])}else b.on(k,
h,function(a){for(var d=f.length-1;d>=0;d--)c.event.eventParser.parse(f[d][0],f[d][1],a)})}});
Jx().$package(function(c){c.number=c.number||{};c.number.format=function(b,c){for(var o=b?b.toString().split("."):["0"],k=c?c.split("."):[""],e="",l=o[0],h=k[0],f=l.length-1,q=!1,i=h.length-1;i>=0;i--)switch(h.substr(i,1)){case "":f>=0&&(e=l.substr(f--,1)+e);break;case "0":e=f>=0?l.substr(f--,1)+e:"0"+e;break;case ",":q=!0,e=","+e}if(f>=0)if(q)for(h=l.length;f>=0;f--)e=l.substr(f,1)+e,f>0&&(h-f)%3==0&&(e=","+e);else e=l.substr(0,f+1)+e;e+=".";l=o.length>1?o[1]:"";h=k.length>1?k[1]:"";for(i=f=0;i<
h.length;i++)switch(h.substr(i,1)){case "":f<l.length&&(e+=l.substr(f++,1));break;case "0":e+=f<l.length?l.substr(f++,1):"0"}return e.replace(/^,+/,"").replace(/\.$/,"")}});
Jx().$package(function(c){c.string=c.string||{};var b=c.string,p,o,k,e,l,h,f,q,i,m,n={};p=function(a,d){var b=!/\W/.test(a)?n[a]=n[a]||p(document.getElementById(a).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+a.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');");return d?b(d):
b};o=function(a){return o.RE.test(a)};o.RE=/^(?:ht|f)tp(?:s)?\:\/\/(?:[\w\-\.]+)\.\w+/i;k=function(a){var d=null;if(null!==(d=k.RE.exec(a))){for(var a={},b=0,c=k.SPEC.length;b<c;b++)a[k.SPEC[b]]=d[b+1];d=a}return d};k.SPEC=["scheme","user","pass","host","port","path","query","fragment"];k.RE=/^([^:]+):\/\/(?:([^:@]+):?([^@]*)@)?(?:([^/?#:]+):?(\d*))([^?#]*)(?:\?([^#]+))?(?:#(.+))?$/;e=function(a){return String(a).replace(/^\s+|\s+$/g,"")};l=function(a,d){return encodeURIComponent(String(a))+"="+encodeURIComponent(String(d))};
h=function(a,d){return a.replace(/[^\x00-\xff]/g,{2:"aa",3:"aaa"}[d||2]).length};f=function(a,d){return a.substring(0,a.length-d)};q=function(a){return a.replace(/[&'"<>\/\\\-\x00-\x09\x0b-\x0c\x1f\x80-\xff]/g,function(a){return"&#"+a.charCodeAt(0)+";"}).replace(/ /g,"&nbsp;").replace(/\r\n/g,"<br />").replace(/\n/g,"<br />").replace(/\r/g,"<br />")};i=function(a){return escape(a).replace(/\+/g,"%2B")};m=function(a,d){var b=document.createElement("div");b.style.visibility="hidden";b.style.width="auto";
if(d)b.style.fontSize=d+"px";b.style.position="absolute";b.innerHTML=c.string.encodeHtmlSimple(a);document.body.appendChild(b);var i=b.offsetWidth;document.body.removeChild(b);return i};b.cutByWidth=function(a,d,b){for(var c=a.length;c>=0;--c)if(a=a.substring(0,c),m(a,d)<b)return a;return""};b.toString=function(a){return a+""};b.template=p;b.isURL=o;b.parseURL=k;b.buildURL=function(a){for(var d="",b={},c={},i=0,f=k.SPEC.length;i<f;i++){var m=k.SPEC[i];if(a[m]){switch(m){case "scheme":c[m]="://";break;
case "pass":b[m]=":";case "user":b.host="@";break;case "port":b[m]=":";break;case "query":b[m]="?";break;case "fragment":b[m]="#"}m in b&&(d+=b[m]);m in a&&(d+=a[m]);m in c&&(d+=c[m])}}return d};b.mapQuery=function(a){var d,b,a=a||window.location.href,c=a.indexOf("?"),i=a.substring(c+1).split("&"),f={};if(c===-1)return f;for(a=0;a<i.length;a++)try{if(c=i[a].indexOf("="),d=i[a].substring(0,c),b=i[a].substring(c+1),!(f[d]=unescape(b)))throw Error("uri has wrong query string when run mapQuery.");}catch(m){}return f};
b.test=function(a,d,b){return(typeof d=="string"?RegExp(d,b):d).test(a)};b.contains=function(a,d,b){return b?(b+a+b).indexOf(b+d+b)>-1:a.indexOf(d)>-1};b.trim=e;b.clean=function(a){return e(a.replace(/\s+/g," "))};b.camelCase=function(a){return a.replace(/-\D/g,function(a){return a.charAt(1).toUpperCase()})};b.hyphenate=function(a){return a.replace(/[A-Z]/g,function(a){return"-"+a.charAt(0).toLowerCase()})};b.capitalize=function(a){return a.replace(/\b[a-z]/g,function(a){return a.toUpperCase()})};
b.escapeRegExp=function(a){return a.replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")};b.toInt=function(a,d){return parseInt(a,d||10)};b.toFloat=function(a){return parseFloat(a)};b.toSingleLine=function(a){return String(a).replace(/\r/gi,"").replace(/\n/gi,"")};b.toHtml=function(a){return String(a).replace(/&/gi,"&amp;").replace(/\\/gi,"&#92;").replace(/\'/gi,"&#39;").replace(/\"/gi,"&quot;").replace(/</gi,"&lt;").replace(/>/gi,"&gt;").replace(/ /gi,"&nbsp;").replace(/\r\n/g,"<br />").replace(/\n\r/g,"<br />").replace(/\n/g,
"<br />").replace(/\r/g,"<br />")};b.toTitle=function(a){return String(a).replace(/\\/gi,"\\").replace(/\'/gi,"'").replace(/\"/gi,"'")};b.toQueryPair=l;b.toQueryString=function(a){var d=[],b;for(b in a)d.push(l(b,a[b]));return d.join("&")};b.hexToRgb=function(a,d){var b=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);return b?b.slice(1).hexToRgb(d):null};b.rgbToHex=function(a,d){var b=a.match(/\d{1,3}/g);return b?b.rgbToHex(d):null};b.stripScripts=function(a,d){var b="",c=a.replace(/<script[^>]*>([\s\S]*?)<\/script>/gi,
function(a,d){b+=d+"\n";return""});d===!0?$exec(b):$type(d)=="function"&&d(b,c);return c};b.substitute=function(a,d,b){return a.replace(b||/\\?\{([^{}]+)\}/g,function(a,b){return a.charAt(0)=="\\"?a.slice(1):d[b]!=void 0?d[b]:""})};b.replaceAll=function(a,d,b,c){return RegExp.prototype.isPrototypeOf(d)?a.replace(d,b):a.replace(RegExp(d,c?"gi":"g"),b)};b.byteLength=h;b.cutRight=f;b.isNumber=function(a){return a.search(/^\d+$/)!==-1?!0:!1};b.isEmail=function(a){return a.search(/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/)!==
-1?!0:!1};b.cutByBytes=function(a,d){for(var b=a;h(b)>d;)b=f(b,1);return b};b.encodeHtmlSimple=function(a){a=a.replace(/&/g,"&amp;");a=a.replace(/>/g,"&gt;");a=a.replace(/</g,"&lt;");a=a.replace(/"/g,"&quot;");return a=a.replace(/'/g,"&#39;")};b.decodeHtmlSimple=function(a){a=a.replace(/&amp;/g,"&");a=a.replace(/&gt;/g,">");a=a.replace(/&lt;/g,"<");a=a.replace(/&quot;/g,'"');return a=a.replace(/&#39;/g,"'")};b.decodeHtmlSimple2=function(a){a=a.replace(/&amp;/g,"&");a=a.replace(/&gt;/g,">");a=a.replace(/&lt;/g,
"<");a=a.replace(/\\\\"/g,'"');return a=a.replace(/\\\\'/g,"'")};b.encodeHtmlAttributeSimple=function(a){a=a.replace(/&/g,"&amp;");a=a.replace(/>/g,"&gt;");a=a.replace(/</g,"&lt;");a=a.replace(/"/g,"&quot;");a=a.replace(/'/g,"&#39;");a=a.replace(/=/g,"&#61;");return a=a.replace(/`/g,"&#96;")};b.encodeHtmlAttribute=function(a){return a.replace(/[&'"<>\/\\\-\x00-\x1f\x80-\xff]/g,function(a){return"&#"+a.charCodeAt(0)+";"})};b.encodeHtml=q;b.encodeScript=function(a){a+="";return a.replace(/[\\"']/g,
function(a){return"\\"+a}).replace(/%/g,"\\x25").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\x01/g,"\\x01")};b.encodeHrefScript=function(a){return q(i(escScript(a)))};b.encodeRegExp=function(a){return a.replace(/[\\\^\$\*\+\?\{\}\.\(\)\[\]]/g,function(a){return"\\"+a})};b.encodeUrl=i;b.encodeUriComponent=function(a){a=encodeURIComponent(a);a=a.replace(/~/g,"%7E");a=a.replace(/!/g,"%21");a=a.replace(/\*/g,"%2A");a=a.replace(/\(/g,"%28");a=a.replace(/\)/g,"%29");a=a.replace(/'/g,"%27");a=a.replace(/\?/g,
"%3F");return a=a.replace(/;/g,"%3B")};b.vaildTencentUrl=function(a){return/^(https?:\/\/)?[\w\-.]+\.(qq|paipai|soso|taotao)\.com($|\/|\\)/i.test(a)||/^[\w][\w\/\.\-_%]+$/i.test(a)||/^[\/\\][^\/\\]/i.test(a)?!0:!1};b.vaildUrl=function(a){var a=encodeURI(a).replace(/(^\s*)|(\s*$)/g,""),d=/(^[a-zA-Z0-9]+[^.]):/,b=/^[\S.]+\.[\S.]+$/,c=/[\w.]+\/(\S*)/,i=/^[\s*]*javascript[\s*]*:/;!d.test(a)&&!b.test(a)?a="":(d.test(a)||(a="http://"+a),c.test(a)||(a+="/"),i.test(a)&&(a=""));return a};b.getCharWidth=m});
Jx().$package(function(c){var b=window.JSON||{};(function(){function c(b){e.lastIndex=0;return e.test(b)?'"'+b.replace(e,function(b){var c=f[b];return typeof c==="string"?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function o(b,f){var n,a,d,g,j=l,e,k=f[b];k&&typeof k==="object"&&typeof k.toJSON==="function"&&(k=k.toJSON(b));typeof q==="function"&&(k=q.call(f,b,k));switch(typeof k){case "string":return c(k);case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);
case "object":if(!k)return"null";l+=h;e=[];if(Object.prototype.toString.apply(k)==="[object Array]"){g=k.length;for(n=0;n<g;n+=1)e[n]=o(n,k)||"null";d=e.length===0?"[]":l?"[\n"+l+e.join(",\n"+l)+"\n"+j+"]":"["+e.join(",")+"]";l=j;return d}if(q&&typeof q==="object"){g=q.length;for(n=0;n<g;n+=1)a=q[n],typeof a==="string"&&(d=o(a,k))&&e.push(c(a)+(l?": ":":")+d)}else for(a in k)Object.hasOwnProperty.call(k,a)&&(d=o(a,k))&&e.push(c(a)+(l?": ":":")+d);d=e.length===0?"{}":l?"{\n"+l+e.join(",\n"+l)+"\n"+
j+"}":"{"+e.join(",")+"}";l=j;return d}}var k=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,l,h,f={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},q;if(typeof b.stringify!=="function")b.stringify=function(b,c,f){var a;h=l="";if(typeof f==="number")for(a=0;a<f;a+=1)h+=" ";else typeof f===
"string"&&(h=f);if((q=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return o("",{"":b})};if(typeof b.parse!=="function")b.parse=function(b,c){function f(a,b){var i,h,e=a[b];if(e&&typeof e==="object")for(i in e)Object.hasOwnProperty.call(e,i)&&(h=f(e,i),h!==void 0?e[i]=h:delete e[i]);return c.call(a,b,e)}var a;k.lastIndex=0;k.test(b)&&(b=b.replace(k,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return a=eval("("+b+")"),typeof c==="function"?f({"":a},""):a;throw new SyntaxError("JSON.parse");}})();c.json=b});
Jx().$package(function(c){var b=c.dom.id,p=c.dom,o=c.event,k;if(typeof window.XMLHttpRequest==="undefined")window.XMLHttpRequest=function(){return new window.ActiveXObject(navigator.userAgent.indexOf("MSIE 5")>=0?"Microsoft.XMLHTTP":"Msxml2.XMLHTTP")};c.http=c.http||{};k=function(h,f,e){var i,m,n,a,d=document.getElementsByTagName("head")?document.getElementsByTagName("head")[0]:document.documentElement,g,j=!1,l=!1,e=e||{};n=e.isDefer||!1;m=e.query||null;arguments=e.arguments||null;var u=e.onSuccess||
function(){},w=e.onError||function(){},s=e.onComplete||function(){},r,t=e.onTimeout||function(){},x=e.timeout,y=e.charset?e.charset:"utf-8",A=e.win||window,z,f=f||"";m!==null&&(f=f+"?"+m);a=k.Id++;r=function(a){(a=b("jet_load_"+a))&&d.removeChild(a)};m=function(d,b,c){return p.node("link",{id:"jet_load_"+a,type:"text/css",charset:c||"utf-8",rel:"stylesheet",href:d},b)};h==="script"?i=e.node||function(d,b,c,g){d=p.node("script",{id:"jet_load_"+a,type:"text/javascript",charset:c||"utf-8",src:d},b);
g&&d.setAttribute("defer","defer");return d}(f,A,y,n):h==="css"&&(i=e.node||m(f,A,y));if(c.browser.engine.trident&&parseInt(c.browser.ie)<9)i.onreadystatechange=function(){var d=this.readyState;if(d==="loaded"||d==="complete")if(i.onreadystatechange=null,!j)l=!0,window.clearTimeout(g),g=null,z={},z.id=a,z.uri=f,z.arguments=arguments,u(z),s(z)};else if(c.browser.engine.webkit)o.on(i,"load",function(){var d;if(!j)l=!0,window.clearTimeout(g),g=null,d={},d.id=a,d.uri=f,d.arguments=arguments,u(d),s(d),
h==="script"&&r(a)});else i.onload=function(){var d;if(!j)l=!0,window.clearTimeout(g),g=null,d={},d.id=a,d.uri=f,d.arguments=e.arguments,u(d),s(d),h==="script"&&r(a)},i.onerror=function(d){var b;if(!j)l=!0,window.clearTimeout(g),g=null,b={},b.id=a,b.uri=f,b.arguments=arguments,b.error=d,w(b),s(b),r(a)};if(e.node)if(h==="script")i.src=f;else{if(h==="css")i.href=f}else d.appendChild(i);h==="script"&&x&&(g=window.setTimeout(function(){var d;if(!l)j=!0,d={},d.uri=f,d.arguments=arguments,t(d),s(d),r(a)},
x));n=function(a){this._node=a;this._head=d};n.prototype={abort:function(){this._node.src="";this._head.removeChild(this._node);delete this._node}};return new n(i)};k.Id=0;var e,l={_iframes:[],_tick:0,_select:function(){this._tick++;return this._iframes[(this._tick-1)%this._len]},init:function(b){if(this._isInit!=!0){this._len=b;for(var c=document.body,k=0;k<b;k++)e=p.node("div",{"class":"RPCService_hDiv"}),p.hide(e),e.innerHTML='<iframe id="RPCService_hIframe_'+k+'" name="RPCService_hIframe_'+k+
'" src="'+alloy.CONST.MAIN_URL+'domain.html"></iframe>',c.appendChild(e),this._iframes[k]=[e,null,"RPCService_hIframe_"+k];this._isInit=!0}},take:function(b){var c=this._select();c[1]&&c[0].removeChild(c[1]);b.setAttribute("target",c[2]);c[1]=b;c[0].appendChild(b)}};c.http.ajax=function(b,c){var e,i,m,n=!1,a=!1,c={method:c.method||"GET",data:c.data||null,arguments:c.arguments||null,onSuccess:c.onSuccess||function(){},onError:c.onError||function(){},onComplete:c.onComplete||function(){},onTimeout:c.onTimeout||
function(){},isAsync:c.isAsync||!0,timeout:c.timeout?c.timeout:3E4,contentType:c.contentType?c.contentType:"utf-8",type:c.type||"xml"},b=b||"";m=c.timeout;e=new window.XMLHttpRequest;e.open(c.method,b,c.isAsync);e.setRequestHeader("Content-Type",c.contentType);i=function(a){try{return!a.status&&location.protocol=="file:"||a.status>=200&&a.status<300||a.status==304||navigator.userAgent.indexOf("Safari")>-1&&typeof a.status=="undefined"}catch(b){}return!1};e.onreadystatechange=function(){if(e.readyState==
4){if(!n){var d={};d.responseText=e.responseText;d.responseXML=e.responseXML;d.data=c.data;d.status=e.status;d.uri=b;d.arguments=c.arguments;if(i(e))c.type==="script"&&eval.call(window,data),c.onSuccess(d);else c.onError(d);c.onComplete(d)}a=!0;e=null}};e.send(c.data);window.setTimeout(function(){var d;if(!a)n=!0,d={},d.uri=b,d.arguments=c.arguments,c.onTimeout(d),c.onComplete(d)},m);return e};c.http.comet=function(b,f){var b=b||"",f={method:f.method||"GET",data:f.data||null,arguments:f.arguments||
null,callback:f.callback||function(){},onLoad:f.onLoad||function(){},contentType:f.contentType?f.contentType:"utf-8"},e;if(c.browser.ie){e=new ActiveXObject("htmlfile");e.open();e.close();var i=e.createElement("div");e.appendChild(i);e.parentWindow._parent=self;i.innerHTML='<iframe id="_cometIframe" src="'+b+"?callback=window.parent._parent."+f.callback+'"></iframe>';e=e.getElementById("_cometIframe")}else e=p.node("iframe"),e.setAttribute("id","_cometIframe"),e.setAttribute("src",b+"?callback=window.parent._parent."+
f.callback),e.style.position="absolute",e.style.visibility="hidden",e.style.left=e.style.top="-999px",e.style.width=e.style.height="1px",document.body.appendChild(e),self._parent=self;o.on(e,"load",f.onLoad);return e};c.http.load=k;c.http.loadCss=function(b,c){return k("css",b,c)};c.http.loadScript=function(b,c){return k("script",b,c)};c.http.formSend=function(b,c){l.init(2);var e={method:c.method||"GET",enctype:c.enctype||"",data:c.data||{},onSuccess:c.onSuccess||function(){},onError:c.onError||
function(){},onComplete:c.onComplete||function(){},onTimeout:c.onTimeout||function(){},timeout:c.timeout?c.timeout:1E4},i=p.node("form",{"class":"RPCService_form",method:e.method,action:b+"?t="+(new Date).getTime(),enctype:e.enctype});if(Object.prototype.toString.call(e.data).indexOf("String")>-1){var m=p.node("input");m.type="text";m.name=e.data;i.appendChild(m)}else for(var n in e.data)m=p.node("input"),m.type="text",m.name=n,m.setAttribute("value",e.data[n]),i.appendChild(m);l.take(i);i.submit()}});
Jx().$package(function(c){var b=function(){function b(m,n){n=n||document;if(!/^[\w\-_#]+$/.test(m)&&n.querySelectorAll)return c(n.querySelectorAll(m));if(m.indexOf(",")>-1){for(var a=m.split(/,/g),d=[],g=0,j=a.length;g<j;++g)d=d.concat(b(a[g],n));return i(d)}a=m.match(e);g=a.pop();d=(g.match(h)||q)[1];j=!d&&(g.match(l)||q)[1];g=!d&&(g.match(f)||q)[1];if(j&&!g&&n.getElementsByClassName)g=c(n.getElementsByClassName(j));else{g=!d&&c(n.getElementsByTagName(g||"*"));if(j){for(var j=RegExp("(^|\\s)"+j+
"(\\s|$)"),v=-1,u,w=-1,s=[];u=g[++v];)j.test(u.className)&&(s[++w]=u);g=s}if(d)return(a=n.getElementById(d))?[a]:[]}return a[0]&&g[0]?k(a,g):g}function c(b){try{return Array.prototype.slice.call(b)}catch(i){for(var a=[],d=0,g=b.length;d<g;++d)a[d]=b[d];return a}}function k(b,c,a){var d=b.pop();if(d===">")return k(b,c,!0);for(var g=[],i=-1,e=(d.match(h)||q)[1],o=!e&&(d.match(l)||q)[1],d=!e&&(d.match(f)||q)[1],p=-1,s,r,t,d=d&&d.toLowerCase();s=c[++p];){r=s.parentNode;do if(t=(t=(t=!d||d==="*"||d===
r.nodeName.toLowerCase())&&(!e||r.id===e))&&(!o||RegExp("(^|\\s)"+o+"(\\s|$)").test(r.className)),a||t)break;while(r=r.parentNode);t&&(g[++i]=s)}return b[0]&&g[0]?k(b,g):g}var e=/(?:[\w\-\\.#]+)+(?:\[\w+?=([\'"])?(?:\\\1|.)+?\1\])?|\*|>/ig,l=/^(?:[\w\-_]+)?\.([\w\-_]+)/,h=/^(?:[\w\-_]+)?#([\w\-_]+)/,f=/^([\w\*\-_]+)/,q=[null,null],i=function(){var b=+new Date,c=function(){var a=1;return function(d){var c=d[b],i=a++;return!c?(d[b]=i,!0):!1}}();return function(a){for(var d=a.length,g=[],i=-1,e=0,f;e<
d;++e)f=a[e],c(f)&&(g[++i]=f);b+=1;return g}}();return b}();c.dom.mini=b});
Jx().$package(function(c){c.array=c.array||{};var b=c.array,p,o,k,e,l,h,f,q,i,m,n,a;p=Array.prototype.indexOf?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.indexOf.apply(arguments[0],a)}:function(a,b,c){for(c==null?c=0:c<0&&(c=Math.max(0,a.length+c));c<a.length;c++)if(a[c]===b)return c;return-1};o=Array.prototype.lastIndexOf?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.lastIndexOf.apply(arguments[0],a)}:function(a,b,c){for(c==null?
c=a.length-1:c<0&&(c=Math.max(0,a.length+c));c>=0;c--)if(a[c]===b)return c;return-1};k=Array.prototype.forEach?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.forEach.apply(arguments[0],a)}:function(a,b,c){var i=a.length;if(typeof b!="function")throw new TypeError;for(var e=0;e<i;e++)e in a&&b.call(c,a[e],e,a)};e=Array.prototype.filter?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.filter.apply(arguments[0],a)}:function(a,b,c){var i=
a.length;if(typeof b!="function")throw new TypeError;for(var e=[],f=0;f<i;f++)if(f in a){var m=a[f];b.call(c,m,f,a)&&e.push(m)}return e};l=Array.prototype.some?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.some.apply(arguments[0],a)}:function(a,b,c){var i=a.length;if(typeof b!="function")throw new TypeError;for(var e=0;e<i;e++)if(e in a&&b.call(c,a[e],e,a))return!0;return!1};h=Array.prototype.map?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.map.apply(arguments[0],
a)}:function(a,b,c){var i=a.length;if(typeof b!="function")throw new TypeError;for(var e=Array(i),f=0;f<i;f++)f in a&&(e[f]=b.call(c,a[f],f,a));return e};f=Array.prototype.every?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.every.apply(arguments[0],a)}:function(a,b,c){var i=a.length;if(typeof b!="function")throw new TypeError;for(var e=0;e<i;e++)if(e in a&&!b.call(c,a[e],e,a))return!1;return!0};q=Array.prototype.reduce?function(){var a=Array.prototype.slice.call(arguments,
1);return Array.prototype.reduce.apply(arguments[0],a)}:function(a,b){var c=a.length>>>0;if(typeof b!="function")throw new TypeError;if(c==0&&arguments.length==2)throw new TypeError;var i=0;if(arguments.length>=3)var e=arguments[2];else{do{if(i in a){e=a[i++];break}if(++i>=c)throw new TypeError;}while(1)}for(;i<c;i++)i in a&&(e=b.call(null,e,a[i],i,a));return e};i=Array.prototype.reduceRight?function(){var a=Array.prototype.slice.call(arguments,1);return Array.prototype.reduceRight.apply(arguments[0],
a)}:function(a,b){var c=a.length>>>0;if(typeof b!="function")throw new TypeError;if(c==0&&arguments.length==2)throw new TypeError;c-=1;if(arguments.length>=3)var i=arguments[2];else{do{if(c in a){i=a[c--];break}if(--c<0)throw new TypeError;}while(1)}for(;c>=0;c--)c in a&&(i=b.call(null,i,a[c],c,a));return i};m=function(a){var b=c.$typeof(a);return b?b!="array"&&b!="arguments"?[a]:a:[]};n=function(a,b){return p(a,b)>-1};a=function(a){for(var b=[],c=0,i=a.length;c<i;c++)n(b,a[c])||b.push(a[c]);return b};
b.indexOf=p;b.lastIndexOf=o;b.forEach=k;b.filter=e;b.some=l;b.map=h;b.every=f;b.reduce=q;b.reduceRight=i;b.toArray=m;b.remove=function(a,b){var b=m(b),c,i,e=!1;for(c=0;c<b.length;c++)for(i=0;i<a.length;i++)a[i]===b[c]&&(a.splice(i,1),e=!0);return e};b.replace=function(a,b,c){for(;0<a.length;ij++)if(a[0]===b)return a[0]=c,!0;return!1};b.bubbleSort=function(a,b){for(var b=b||function(a,b){return a-b},c=a.length,i,e,f=0;f<c-1;f++){e=!1;for(var m=c-1;m>f;m--)b(a[m],a[m-1])<0&&(e=!0,i=a[m-1],a[m-1]=a[m],
a[m]=i);if(!e)break}return a};b.binarySearch=function(a,b,c){for(var i=0,e=a.length,f=Math.floor(a.length/2);e!=f;)c(b,a[f])>0?i=f+1:e=f,f=Math.floor((i+e)/2);return f};b.contains=n;b.uniquelize=a;b.intersect=function(a,b){for(var c=[],i=0,e=a.length;i<e;i++)n(b,a[i])&&c.push(a[i]);return c};b.minus=function(a,b){for(var c=[],i=0,e=a.length;i<e;i++)n(b,a[i])||c.push(a[i]);return c};b.union=function(b,c){return a(b.concat(c))}});
Jx().$package(function(c){var b=c.dom.id,p=c.dom,o=c.event,k=c.string,e=c.http,l=this,h=c.string.mapQuery(window.location.search),f=window.open;window.open=function(b,e,h,a){e==void 0&&(e="_blank");h==void 0&&(h="");a==void 0&&(a=!1);return!f(b,e,h,a)?(c.out("\u4f60\u7684\u673a\u5668\u4e0a\u6709\u8f6f\u4ef6\u62e6\u622a\u4e86\u5f39\u51fa\u7a97\u53e3"),!1):!0};var q=new c.Class({_defaultType:3,_defaultTag:"information",_defaultTemplate:"<%=msg%>(<%=type%>#<%=tag%>@<%=time%>)",TYPE:["PROFILE","WARNING",
"ERROR","INFO","DEBUG"],init:function(b){this.msg=b.msg||"";this.tag=b.tag||this._defaultTag;this.type=c.isUndefined(b.type)?this._defaultType:b.type;this.time=(new Date).valueOf();this._template=b.template||this._defaultTemplate},format:function(b,c,e){e=e||this._template;return c?k.encodeHtml(k.template(e,b)):k.template(e,b)},parseOption:function(){return{msg:this.msg,time:this.time,type:this.TYPE[this.type],tag:this.tag}},toString:function(b,c){return this.format(this.parseOption(),b,c||this._template)}});
c.config={debugLevel:1};c.console={};c.Report={receive:c.emptyFunc,addRule:c.emptyFunc};c.extend(c.console,{_isCreated:!1,_maxLength:1E3,_html:'<div id="ConsoleBoxHead" class="consoleBoxHead">\t\t\t\t\t\t<a href="###" id="ConsoleCloseButton" class="consoleCloseButton" title="\u5173\u95ed">X</a>\t\t\t\t\t\t<a href="###" id="ConsoleClearButton" class="consoleCloseButton" title="\u6e05\u9664\u6240\u6709\u65e5\u5fd7">cls</a>\t\t\t\t\t\t<a href="###" id="ConsoleRefreshButton" class="consoleCloseButton" title="\u8fd8\u539f\u6240\u6709\u65e5\u5fd7">r</a>\t\t\t\t\t\t<a href="###" id="ConsoleHelpButton" class="consoleCloseButton" title="\u63a7\u5236\u53f0\u5e2e\u52a9">H</a>\t\t\t\t\t\t<h5 class="title" title="\u63a7\u5236\u53f0">Console</h5>\t\t\t\t\t</div>\t\t\t\t\t<div id="consoleMain" class="consoleMain">\t\t\t\t\t\t<ul id="ConsoleOutput" class="consoleOutput"></ul>\t\t\t\t\t</div>\t\t\t\t\t<div class="consoleInputBox">\t\t\t\t\t\t&gt;<input id="ConsoleInput" class="consoleInput" title="\u8bf7\u8f93\u5165\u63a7\u5236\u53f0\u6307\u4ee4\u6216\u8005Javascript\u8bed\u53e5..." />\t\t\t\t\t</div>',
_opened:!1,_log_record:[],_cmd_history:[],_cmd_last_index:0,isCustomConsole:!0,_templateArr:["<%=msg%>","<%=msg%>(<%=type%>#<%=tag%>@<%=time%>)"],_templateType:0,_typeInfo:[["log_profile_type","\u2514"],["log_warning_type","!"],["log_error_type","x"],["log_info_type","i"],["log_debug_type","\u221a"]],TYPE:{PROFILE:0,WARNING:1,ERROR:2,INFO:3,DEBUG:4},show:function(){this._isCreated||this._create();this._opened=!0;this._main.style.display="block";this.render();window.setTimeout(c.bind(this.focusCommandLine,
this),0)},hide:function(b){b&&b.preventDefault();this.clear();c.console._main.style.display="none";c.console._opened=!1},enable:function(){c.option.console=!0;this.show()},disable:function(){c.option.console=!1;this.hide()},_init:function(){o.on(document,"keydown",c.bind(this.handleDocumentKeydown,this));c.option.console&&this.show();this.setToDebug()},_create:function(){e.loadCss(c.path+"assets/jet.css");this._main=document.createElement("div");this._main.id="JxConsole";this._main.style.display=
"none";this._main.className="consoleBox";this._main.innerHTML=this._html;window.document.body.appendChild(this._main);var i=p.getClientWidth(),f=p.getClientHeight(),i=i-210-300;p.setStyle(this._main,"top",f-50-310+"px");p.setStyle(this._main,"left",i+"px");this._headEl=b("ConsoleBoxHead");this._inputEl=b("ConsoleInput");this._closeButtonEl=b("ConsoleCloseButton");this._clsButtonEl=b("ConsoleClearButton");this._refreshButtonEl=b("ConsoleRefreshButton");this._helpButtonEl=b("ConsoleHelpButton");this._outputEl=
b("ConsoleOutput");this._consoleMainEl=b("consoleMain");c.ui.Drag&&new c.ui.Drag(this._headEl,this._main);o.on(this._inputEl,"keyup",c.bind(this.onInputKeyup,this));o.on(this._clsButtonEl,"click",c.bind(this.clear,this));o.on(this._refreshButtonEl,"click",c.bind(this.refresh,this));o.on(this._helpButtonEl,"click",c.bind(this.help,this));o.on(this._closeButtonEl,"click",c.bind(this.hide,this));f={hScrollbar:!0,vScrollbar:!0,checkDOMChanges:!1,desktopCompatibility:!0};if(c.browser.mobileSafari&&c.ui.iScroll&&
!this.consoleScroller)this.consoleScroller=new c.ui.iScroll(this._outputEl,f),c.debug("!!!!2","console");this._isCreated=!0},handleDocumentKeydown:function(b){switch(b.keyCode){case 192:b.ctrlKey&&b.shiftKey&&(this.toggleShow(),b.preventDefault())}},focusCommandLine:function(){this._inputEl.focus()},toggleShow:function(){this._opened?this.hide():this.show()},outConsoleShow:function(b,e){this.outConsole(b,e);!this._opened&&c.option.console&&this.show()},outConsole:function(b){if(this._opened){var e=
document.createElement("li");this._outputEl.appendChild(e);var f=c.console._typeInfo[b.type]||c.console._typeInfo[0],a=this._templateArr[this._templateType];e.className=f[0];e.innerHTML='<div class="log_icon" title="'+f[0]+'">'+f[1]+'</div><div class="log_text">'+b.toString(!0,a)+"</div>";this.consoleScroller&&this.consoleScroller.refresh();this._consoleMainEl.scrollTop=this._consoleMainEl.scrollHeight}},print:function(b){var c=document.createElement("li");this._outputEl.appendChild(c);c.innerHTML=
b;this._consoleMainEl.scrollTop=this._consoleMainEl.scrollHeight},out:function(b,c,e){var a=this._templateArr[this._templateType],b=new q({msg:b,tag:c,type:e});this.logRecord(b);h&&h.consolefilter?b.tag==h.consolefilter&&(this.isCustomConsole?this.outConsole(b):l.console.log(b.toString(!1,a))):this.isCustomConsole?this.outConsole(b):l.console.log(b.toString(!1,a))},profile:function(b,c){this.out(b,c||"system",0)},warn:function(b,c){this.out(b,c,1)},error:function(b,c){this.out(b,c,2)},info:function(b,
c){this.out(b,c,3)},debug:function(b,c){this.out(b,c,4)},setToDebug:function(){this.isCustomConsole=h.console&&h.console=="firebug"?!1:!0},setToNoDebug:function(){this.out=c.emptyFunc},logRecord:function(b){this._log_record.push(b);h.console||this._log_record.length>this._maxLength&&this._log_record.shift()},setTemplate:function(b){if(this._templateArr[b])this._templateType=b},filter:function(b){var e=RegExp(b,"i"),f=[];c.array.forEach(this._log_record,function(a){var b=a.toString(!0);e.test(b)&&
f.push(a)});return f},filterByType:function(b,e){var f=[],b=b||[];c.array.forEach(b,function(a){var b=!1;c.array.forEach(e,function(c){a.type==c&&(b=!0)});b&&f.push(a)});return f},filterByTag:function(b,e){var f=[],b=b||[];c.array.forEach(b,function(a){var b=!1;c.array.forEach(e,function(c){a.tag==c&&(b=!0)});b&&f.push(a)});return f},filterByMsg:function(b,e){var f=[],b=b||[];c.array.forEach(b,function(a){var b=!1;c.array.forEach(e,function(c){a.msg.indexOf(c)>-1&&(b=!0)});b&&f.push(a)});return f},
getReport:function(b,e,f){var a=[],d=this._log_record,g=this;!b||b==""?b=!1:c.isArray(b)||(b=[b]);!e||e==""?e=!1:c.isArray(e)||(e=[e]);!f||f==""?f=!1:c.isArray(f)||(f=[f]);b&&(d=this.filterByType(d,b));e&&(d=this.filterByTag(d,e));f&&(d=this.filterByMsg(d,f));c.array.forEach(d,function(b){a.push(b.toString(!1,g._templateArr[1]))});return a.join(",")},render:function(b,e){b=b||this._log_record;e||(b=b.slice(-15));var f=this;f.clear();c.array.forEach(b,function(a){f.outConsole(a)})},clear:function(b){b&&
b.preventDefault();c.console._outputEl.innerHTML=""},refresh:function(b){b&&b.preventDefault();this.clear();this.render()},help:function(b){b&&b.preventDefault();this.print("&lt;&lt; Console Help &gt;&gt;<br/>\t\t\t\t\t\t\t\thelp|h  : \u63a7\u5236\u53f0\u5e2e\u52a9<br/>\t\t\t\t\t\t\t\tclear|cls : \u6e05\u7a7a\u63a7\u5236\u53f0\u8f93\u51fa<br/>\t\t\t\t\t\t\t\trefresh|r : \u5237\u65b0\u63a7\u5236\u53f0\u8f93\u51fa<br/>\t\t\t\t\t\t\t\tfilter|f : \u8fc7\u6ee4\u63a7\u5236\u53f0\u8f93\u51fa<br/>\t\t\t\t\t\t\t\tsetTemplate|s : \u8bbe\u7f6e\u8f93\u51fa\u6a21\u7248\u7c7b\u578b<br/>\t\t\t\t\t\t\t\thide  : \u9690\u85cf\u63a7\u5236\u53f0\uff0c\u6216\u8005\u4f7f\u7528 Ctrl+Shift+`[~] \u5feb\u6377\u952e")},
onInputKeyup:function(b){switch(b.keyCode){case 13:this._cmd_history.push(c.console._inputEl.value);this._cmd_last_index=this._cmd_history.length;this._execCommand(c.console._inputEl.value);break;case 38:if(this._cmd_history.length==0)break;b="";this._cmd_last_index>0?(this._cmd_last_index--,b=this._cmd_history[this._cmd_last_index]):this._cmd_last_index=-1;c.console._inputEl.value=b;break;case 40:if(this._cmd_history.length==0)break;b="";this._cmd_last_index<this._cmd_history.length-1?(this._cmd_last_index++,
b=this._cmd_history[this._cmd_last_index]):this._cmd_last_index=this._cmd_history.length;c.console._inputEl.value=b}},_execCommand:function(b){b=="help"||b=="h"?this.help():b=="clear"||b=="cls"?c.console.clear():b=="hide"?c.console.hide():b=="refresh"||b=="r"?this.refresh():b=="showall"||b=="sa"?(this.clear(),this.render(null,!0)):RegExp(/^(?:filter|f)(?:\(|\s+)(.+)(?:\)|\s*)$/i).test(b)?(b=eval("this.filter('"+RegExp.$1+"')"),b.length>0?this.render(b,!0):(this.clear(),this.out("NO RESULT!",1))):
RegExp(/^(?:setTemplate|s)(?:\(|\s+)(\d+)(?:\)|\s*)$/i).test(b)?(this.setTemplate(parseInt(RegExp.$1)),this.refresh()):this._execScript(b);c.console._inputEl.value=""},_execScript:function(b){var e='<span style="color:#ccff00">'+b+"</span><br/>";try{e+=(eval(b)||"").toString().replace(/</g,"&lt;").replace(/>/g,"&gt;"),c.console.print(e,0)}catch(f){e+=f.description,c.console.print(e,1)}}});c.profile=c.console.profile;c.warn=c.console.warn;c.error=c.console.error;c.info=c.console.info;c.debug=c.console.debug;
o.onDomReady(function(){c.console._init();if(h.console=="true")c.console=c.extend(c.console,{profile:c.emptyFunc,warn:c.emptyFunc,error:c.emptyFunc,info:c.emptyFunc,debug:c.emptyFunc}),c.console.show()});h.console&&h.console=="firebug"&&(l.console||e.loadScript(c.path+"firebug/firebug-lite.js",{onSuccess:function(){if(firebug)firebug.env.height=220,firebug.env.css="../../source/firebug/firebug-lite.css",c.out("...\u63a7\u5236\u53f0\u5f00\u542f"),c.out("...\u6d4b\u8bd5\u6210\u529f")}}));c.runtime=
function(){function b(){return c.config.debugLevel>0}function e(a,d){var g;b()?g=a+"\n=STACK=\n"+f():d=="error"&&(g=a);c.Debug.errorLogs.push(g)}function f(a,b){function c(a,b){if(a.stack)return a.stack;else if(a.message.indexOf("\nBacktrace:\n")>=0){var d=0;return a.message.split("\nBacktrace:\n")[1].replace(/\s*\n\s*/g,function(){d++;return d%2==0?"\n":" @ "})}else{for(var e=b.callee==f?b.callee.caller:b.callee,g=e.arguments,i=[],h=0,m=g.length;h<m;h++)i.push(typeof g[h]=="undefined"?"<u>":g[h]===
null?"<n>":g[h]);g=/function\s+([^\s\(]+)\(/;return((g.test(e.toString())?g.exec(e.toString())[1]:"<ANON>")+"("+i.join()+");").replace(/\n/g,"")}}var e;if(a instanceof Error&&typeof arguments=="object"&&arguments.callee)e=c(a,b);else try{({}).sds()}catch(i){e=c(i,arguments)}return e.replace(/\n/g," <= ")}return{stack:f,warn:function(a,b){e(write.apply(null,arguments),"warn")},error:function(a,b){e(write.apply(null,arguments),"error")},isDebugMode:b}}()});
Jx().$package("alloy",function(c){var b=this,p=c.event,o=+new Date,k={},e={},l=!1,h=!1,f=[],q=!1,i=[],m=window,n=document,a=location,d=a.protocol,a=a.host,g={PATTERN:/top|parent|frames\[(?:(?:['"][a-zA-Z\d-_%\.]*['"])|\d+)\]/,WQKEY:null,MSGNAME:"crossframe:message",CFPROXY:"alloy.proxy.html",CGI_SERVER:"http://cgi.web2.qq.com/",MAIN_DOMAIN:null,PROXY:null,REGHOST:RegExp("^"+d+"//("+a+")/.*"),REGPROXY:RegExp("^"+d+"//"+a+"/(.+)")},j=function(a){u();h?a.call(b):f.push(a)},v=function(){if(!h&&(h=!0,
f)){for(var a,c=0;a=f[c++];)a.call(b);f=null}},u=function(){if(!l)l=!0,n.attachEvent?(n.attachEvent("onreadystatechange",function(){n.readyState==="complete"&&(n.detachEvent("onreadystatechange",arguments.callee),v())}),n.documentElement.doScroll&&m==m.top&&function(){if(!h){try{n.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}v()}}()):n.addEventListener&&n.addEventListener("DOMContentLoaded",function(){n.removeEventListener("DOMContentLoaded",arguments.callee,!1);
v()},!1),m.attachEvent?m.attachEvent("onload",v):m.addEventListener?m.addEventListener("load",v,!1):m.onload=v},w=function(a,b,d){d=d||{};if(c.isUndefined(d)||c.isUndefined(d.key)||c.isUndefined(d.cmd)||c.isUndefined(d.host))d=null;else{var f={key:d.key,type:d.type,cmd:d.cmd,host:d.host,event:d.event},i=d.type=="event"?e:k;d.proxy&&(f.proxy=d.proxy);!c.isUndefined(d.param)&&(f.param=d.param);if(!c.isUndefined(d.onSuccess)||!c.isUndefined(d.onError)){var h=i[++o]={};!c.isUndefined(d.onSuccess)&&(h.suc=
d.onSuccess);!c.isUndefined(d.onError)&&(h.err=d.onError);f.seq=o}else if(d.cmd=="addEventListener")h=i[++o]={},h.event=d.event,h.handler=d.handler,f.seq=o;else if(d.cmd=="removeEventListener")if(c.isUndefined(d.handler))for(h in e)i=e[h],i.event===d.event&&delete e[h];else for(h in e)i=e[h],i.event===d.event&&i.handler===d.handler&&delete e[h];d=c.json.stringify(f)}cfProxys=n.getElementById("webqq_cfproxys")||n.body;if(!c.isUndefined(a)&&!c.isUndefined(b)&&g.PATTERN.test(a)){if(!d)throw Error("error message!");
c.isUndefined(m.postMessage)?(a="http://"+b+"/"+g.CFPROXY+"#"+r({target:a,host:b}),b=n.createElement("div"),b.innerHTML='<iframe name="'+encodeURIComponent(d)+'" src="'+a+'" onload="alloy.removeCF(this)"></iframe>',cfProxys.appendChild(b)):(a=eval(a),a.postMessage(d,"http://"+b))}},s=function(){},r=function(a){var b=[],c;for(c in a)b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b.join("&")},t={};this.CONST={};this.onDomReady=j;this.onReady=function(a){if(c.isFunction(a))if(q)this.onDomReady(a);
else i.push(a)};this.getScript=function(a){var a=a||{},b=!1,c=a.url||"",d=a.type||"script",e=a.param||{},f=a.onSuccess||s,g,i=n.getElementsByTagName("head")[0]||n.documentElement,h=n.createElement("script");if(a.charset)h.charset=a.charset;c+=(/\?/.test(c)?"&":"?")+r(e);if(d==="jsonp")g="jsonp"+o++,m[g]=function(a){f(a);m[g]=void 0;try{delete m[g]}catch(b){}i&&i.removeChild(h)},c+="&retype=2&callback=?",c=c.replace(/\=\?(&|$)/,"="+g+"$1");else if(d==="script")h.onload=h.onreadystatechange=function(){if(!b&&
(!this.readyState||this.readyState==="loaded"||this.readyState==="complete"))b=!0,f(),h.onload=h.onreadystatechange=null,i&&h.parentNode&&i.removeChild(h)};h.src=c;i.insertBefore(h,i.lastChild)};this.registerSDK=function(a){for(var b=0,d=a.length,e;b<d;b++)if(e=a[b],!c.isUndefined(e[0])&&c.isFunction(e[1]))t[String(e[0])]={api:e[1]};else if(!c.isUndefined(e[0])&&!c.isUndefined(e[1])&&!c.isUndefined(e[2])&&(t[String(e[0])]={method:String(e[1]),url:String(e[2])},!c.isUndefined(e[3])))t[String(e[0])].makeParam=
e[3]};this.api=function(a,b){if(c.isUndefined(a))throw Error("api param error!");var d=g.REGHOST.exec(location.href);if(d){var e=t[a],f;if(e){if(e.api){e.api(b);return}if(!g.APPID)throw Error("no openkey!");f={param:{method:e.method,url:e.url,param:{appid:g.APPID}}};c.isUndefined(e.makeParam)?c.extend(f.param.param,b.param):(e=e.makeParam(b.param),c.extend(f.param.param,c.isObject(e)?e:{r:e}));!c.isUndefined(b.onSuccess)&&(f.onSuccess=b.onSuccess);!c.isUndefined(b.onError)&&(f.onError=b.onError);
b=f;a="util.cgiSend"}d={key:g.WQKEY,type:"method",cmd:a,host:d[1]};g.PROXY&&(d.proxy=g.PROXY);if(!c.isUndefined(b))!c.isUndefined(b.param)&&(d.param=b.param),!c.isUndefined(b.onSuccess)&&(d.onSuccess=b.onSuccess),!c.isUndefined(b.onError)&&(d.onError=b.onError);w("parent",g.MAIN_DOMAIN,d)}};this.setProxy=function(a){if(a=g.REGPROXY.exec(a))g.PROXY=a[1]};this.removeCF=function(a){a&&m.setTimeout(function(){var b=a.parentNode;b.parentNode.removeChild(b);a=null},1E3)};this.addEventListener=function(a,
d){b.api("report.apiCallCnt",{param:{event:a}});if(c.isUndefined(a)||c.isUndefined(d))throw Error("addEventListener param error!");var e=g.REGHOST.exec(location.href);if(e)e={key:g.WQKEY,host:e[1],type:"event",cmd:"addEventListener",event:a,handler:d},g.PROXY&&(e.proxy=g.PROXY),w("parent",g.MAIN_DOMAIN,e)};this.removeEventListener=function(a,b){if(c.isUndefined(a))throw Error("removeEventListener param error!");var d=g.REGHOST.exec(location.href);if(d)d={key:g.WQKEY,host:d[1],type:"event",cmd:"removeEventListener",
event:a,handler:b},g.PROXY&&(d.proxy=g.PROXY),w("parent",g.MAIN_DOMAIN,d)};this.on=this.addEventListener;this.off=this.removeEventListener;this.registerSDK([["account.check",function(a){(a.onSuccess||s)(b.CONST)}],["account.bind","POST",g.CGI_SERVER+"api/app/bind",function(a){return c.json.stringify(a)}],["account.unbind","POST",g.CGI_SERVER+"api/app/unbind",function(a){return c.json.stringify(a)}],["system.getToken","POST",g.CGI_SERVER+"api/system/gettoken"]]);(function(a,d){var f=a.name;if(f=="")throw Error("window name error!");
f=c.json.parse(decodeURIComponent(f));if(f.appid&&f.webqqkey&&f.webqqdomain)g.APPID=f.appid,g.WQKEY=f.webqqkey,g.MAIN_DOMAIN=f.webqqdomain,g.MAIN_URL="http://"+g.MAIN_DOMAIN,c.isUndefined(a.postMessage)?j(function(){var a=d.createElement("div"),b=a.style;a.id="webqq_cfproxys";b.width=0;b.height=0;b.display="none";d.body.appendChild(a)}):(f=function(b){if(b.origin!=g.MAIN_URL||!b.source)throw Error("illegal origin or source in onmessage !");b=c.json.parse(b.data);p.notifyObservers(a,g.MSGNAME,b)},
a.attachEvent?a.attachEvent("onmessage",f):a.addEventListener?a.addEventListener("message",f,!1):a.onmessage=f),p.addObserver(a,"loadApp",function(){q=!0;b.onDomReady(function(){if(i){for(var a,b=0;a=i[b++];)a();i=null}})}),j(function(){alloy.system.getLoginState(function(){p.notifyObservers(a,"loadApp",{})});var c,e,f,g=d.getElementsByTagName("head")[0];g&&(c=g.getElementsByTagName("base")[0]);c&&(e=c.getAttribute("target"));f=e==="_blank";p.on(d,"click",function(a){for(var c=a.target;c;){if(c.tagName===
"A"&&(f||c.getAttribute("target")&&c.getAttribute("target").toLowerCase()==="_blank")){a.preventDefault();a.stopPropagation();b.system.openURL({url:c.getAttribute("href")});break}c=c.parentNode}})}),p.addObserver(a,g.MSGNAME,function(a){var b=+a.ret,d=a.seq;if(!c.isUndefined(a)&&!c.isUndefined(b)&&!c.isUndefined(d))a=a.result,b=b===0?"suc":"err",k[d]&&k[d][b]?(k[d][b](a),delete k[d]):e[d]&&e[d].handler&&e[d].handler(a)}),p.on(a,"unload",function(){e=k=null})})(m,n)});
(function(c){for(var b=Jx(),p=b.event,o=[["system.alert"],["system.confirm"],["system.getLoginState"],["system.showLoginBox"],["system.isAppInstalled"],["system.isAppRunning"],["system.isLocked"],["system.openURL"],["system.runApp"],["system.runAppMarket"],["system.runBrowser"],["system.runIME"],["system.runHandWrite"],["system.runQQ"],["system.runSettingCenter"],["system.installApp"],["system.search"],["system.getToken"],["system.getUinAndSkey"],["system.showShareBox"],["system.getAppInfo"],["system.openFile"],
["system.isWebTop"],["window.setExitConfirm"],["window.removeExitConfirm"],["window.close"],["window.fullScreen"],["window.getRunOption"],["window.max"],["window.min"],["window.restore"],["window.setButton"],["window.setCenter"],["window.setCurrent"],["window.setNotCurrent"],["window.setWinSize"],["window.setBodySize"],["window.setBorderOpacity"],["window.setOpacity"],["window.setStyle"],["window.setTitle"],["window.setToolbar"],["window.setToolbarButton"],["window.setXY"],["window.getXY"],["window.getRestoreXY"],
["window.startDrag"],["window.enableIframeDrag",function(c){p.on(c,"drag",function(c){c.preventDefault();c.stopPropagation();(!b.browser.ie||!(b.browser.ie<=6&&(c.target.tagName=="A"||c.target.parentNode&&c.target.parentNode.tagName=="A")))&&alloy.widget.startDrag([c.pageX,c.pageY])})}],["widget.setExitConfirm"],["widget.removeExitConfirm"],["widget.close"],["widget.getRunOption"],["widget.setButton"],["widget.setCurrent"],["widget.setNotCurrent"],["widget.setOpacity"],["widget.setXY"],["widget.getXY"],
["widget.setWinSize"],["widget.setBodySize"],["widget.setBodySize"],["widget.startDrag"],["widget.enableIframeDrag",function(c){p.on(c,"drag",function(c){c.preventDefault();c.stopPropagation();(!b.browser.ie||!(b.browser.ie<=6&&(c.target.tagName=="A"||c.target.parentNode&&c.target.parentNode.tagName=="A")))&&alloy.widget.startDrag([c.pageX,c.pageY])})}],["layout.applyScene"],["layout.applySkin"],["layout.applyTheme"],["layout.applyWallpaper"],["layout.setScene"],["layout.setSkin"],["layout.setTheme"],
["layout.setWallpaper"],["layout.getDesktopSize"],["layout.getAvailSize"],["layout.getClientSize"],["layout.showDesktop"],["sound.play"],["sound.setMute"],["sound.isMute"],["sound.setVolume"],["sound.getVolume"],["account.check"],["account.bind"],["account.unbind"],["report.report2app"],["report.apiCallCnt"],["qq.isLogin"],["account.setSignature"],["user.getNick"],["user.getProfile"],["user.setProfile"],["system.setOpenURL",function(e,f){var h=document,a=function(){},d=function(a){a.preventDefault();
a.stopPropagation();c.system.openURL({url:a.currentTarget.getAttribute("href")});return!1};b.isFunction(e)&&(f=e,e=h);var e=e&&e.nodeType?e:h,f=b.isFunction(f)?f:a,g,j,a=h.getElementsByTagName("head")[0],h=e.getElementsByTagName("a");a&&(g=a.getElementsByTagName("base")[0]);g&&(j=g.getAttribute("target"));g=j==="_blank";j=0;for(var a=h.length,k,l;j<a;j++)if(k=h[j],l=k.getAttribute("target"),l==="_blank"||!l&&g)l=f(k),l!==!1&&p.addEventListener(k,"click",d)}],["component.inviteInstallAppByTips"],["component.inviteInstallAppByC2C"],
["component.shareMsg"],["component.shareMsgByC2C"]],k=function(e){return function(f,h,a){b.isFunction(f)&&(a=a||h,h=f,f=void 0);c.api(e,{param:f,onSuccess:h,onError:a})}},e=function(b,e){return function(){e.apply(this,arguments);c.api("report.apiCallCnt",{param:{cmd:b}})}},l=function(f,h){var l,a,d,g=f.split("."),j=c;l=0;for(a=g.length-1;l<a;l++)d=g[l],j[d]=j[d]||{},j=j[g[l]];d=g[l];j[d]=b.isFunction(j[d])?j[d]:!b.isFunction(h)?k(f):e(f,h)},h=0,f=o.length,q;h<f;h++)q=o[h],l(q[0],q[1])})(alloy);